# Generated by Django 2.0.4 on 2018-04-23 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='分类名')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '产品大分类',
                'verbose_name_plural': '产品大分类',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='未填写。', max_length=200, verbose_name='产品名称')),
                ('sub_title', models.CharField(default='未填写。', max_length=250, verbose_name='小标题')),
                ('orignal_price', models.FloatField(default=0.0, verbose_name='原始价格')),
                ('promote_price', models.FloatField(default=0.0, verbose_name='优惠价格')),
                ('stock', models.CharField(default='0', max_length=30, verbose_name='库存')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('sale_count', models.IntegerField(default=0, verbose_name='销售数量')),
                ('status', models.NullBooleanField(default='未填写。', verbose_name='销售状态')),
                ('business_name', models.CharField(max_length=250, verbose_name='商家名称')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Category', verbose_name='分类')),
            ],
            options={
                'verbose_name': '产品表',
                'verbose_name_plural': '产品表',
            },
        ),
        migrations.CreateModel(
            name='ProductDetailImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='web_site/notfound.png', upload_to='produceImage/Detail')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Product', verbose_name='所属商品')),
            ],
            options={
                'verbose_name': '产品详情图片',
                'verbose_name_plural': '产品详情图片',
            },
        ),
        migrations.CreateModel(
            name='ProductSingleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='image/default.png', upload_to='produceImage/Single')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Product', verbose_name='所属商品')),
            ],
            options={
                'verbose_name': '产品标题图片',
                'verbose_name_plural': '产品标题图片',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='属性')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Category', verbose_name='分类')),
            ],
            options={
                'verbose_name': '产品属性',
                'verbose_name_plural': '产品属性',
            },
        ),
        migrations.CreateModel(
            name='PropertyValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200, verbose_name='属性值')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Product', verbose_name='所属商品')),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Property', verbose_name='属性名')),
            ],
            options={
                'verbose_name': '属性值',
                'verbose_name_plural': '属性值',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评价内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('ratings', models.IntegerField(default=0, verbose_name='评价星')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Product', verbose_name='所属商品')),
            ],
            options={
                'verbose_name': '产品评价',
                'verbose_name_plural': '产品评价',
            },
        ),
    ]
