# Generated by Django 2.0.4 on 2018-04-23 04:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsynMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_time', models.DateTimeField(default=datetime.datetime(2018, 4, 23, 4, 6, 55, 910001, tzinfo=utc), verbose_name='通知时间')),
                ('notify_type', models.CharField(max_length=120, verbose_name='通知类型')),
                ('notify_id', models.CharField(max_length=200, verbose_name='通知校验ID')),
                ('charset', models.CharField(max_length=12, verbose_name='编码格式')),
                ('version', models.CharField(max_length=8, verbose_name='版本')),
                ('sign_type', models.CharField(max_length=12, verbose_name='签名类型')),
                ('sign', models.CharField(max_length=249, verbose_name='签名')),
                ('auth_app_id', models.CharField(max_length=36, verbose_name='授权方的app_id')),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='商家id')),
                ('http_status', models.CharField(blank=True, max_length=30, null=True, verbose_name='http连接状态')),
            ],
        ),
        migrations.CreateModel(
            name='CacheData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='用户id')),
                ('product_id', models.IntegerField(verbose_name='产品id')),
                ('number', models.IntegerField(verbose_name='购买数量')),
                ('cart_time', models.DateTimeField(default=datetime.datetime(2018, 4, 23, 4, 6, 55, 911398, tzinfo=utc), verbose_name='购物车添加时间')),
            ],
            options={
                'verbose_name': '缓存数据',
                'verbose_name_plural': '缓存数据',
            },
        ),
        migrations.CreateModel(
            name='ServiceParam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_no', models.CharField(max_length=120, verbose_name='支付宝交易号')),
                ('app_id', models.CharField(max_length=36, verbose_name='开发者的app_id')),
                ('out_trade_no', models.CharField(max_length=80, verbose_name='商户订单号')),
                ('out_biz_no', models.CharField(max_length=80, verbose_name='商户业务号')),
                ('buyer_id', models.CharField(max_length=30, verbose_name='买家支付宝用户号')),
                ('seller_id', models.CharField(max_length=30, verbose_name='卖家支付宝用户号')),
                ('trade_status', models.CharField(max_length=30, verbose_name='交易状态')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='订单金额')),
                ('receipt_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='实收金额')),
                ('invoice_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='开票金额')),
                ('buyer_pay_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='付款金额')),
                ('point_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='集分宝金额')),
                ('refund_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='总退款金额')),
                ('subject', models.CharField(max_length=200, verbose_name='订单标题')),
                ('body', models.CharField(max_length=249, verbose_name='商品描述')),
                ('gmt_create', models.DateTimeField(default=datetime.datetime(2018, 4, 23, 4, 6, 55, 910730, tzinfo=utc), verbose_name='交易创建时间')),
                ('gmt_payment', models.DateTimeField(default=datetime.datetime(2018, 4, 23, 4, 6, 55, 910757, tzinfo=utc), verbose_name='交易付款时间')),
                ('gmt_refund', models.DateTimeField(default=datetime.datetime(2018, 4, 23, 4, 6, 55, 910775, tzinfo=utc), verbose_name='交易退款时间')),
                ('gmt_close', models.DateTimeField(default=datetime.datetime(2018, 4, 23, 4, 6, 55, 910792, tzinfo=utc), verbose_name='交易结束时间')),
                ('fund_bill_list', models.CharField(max_length=240, verbose_name='支付金额信息')),
                ('voucher_detail_list', models.CharField(max_length=240, verbose_name='优惠券信息')),
                ('passback_params', models.CharField(max_length=240, verbose_name='回传参数')),
            ],
        ),
        migrations.CreateModel(
            name='WebMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_num', models.CharField(default='猫之商城', max_length=200, verbose_name='注册人数')),
                ('oline_num', models.CharField(default='猫之商城', max_length=200, verbose_name='在线人数')),
                ('site_running_time', models.DateTimeField(auto_now_add=True, verbose_name='站点开始运行的时间')),
                ('site_front_status', models.NullBooleanField(default=True, verbose_name='前台站点开启状态')),
                ('site_message', models.CharField(default='无', max_length=250, verbose_name='站点全局信息')),
            ],
            options={
                'verbose_name': '站点相关',
                'verbose_name_plural': '站点相关',
            },
        ),
    ]
