# Generated by Django 2.0.4 on 2018-04-23 05:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20180423_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asynmsg',
            name='notify_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 23, 5, 50, 28, 669538, tzinfo=utc), verbose_name='通知时间'),
        ),
        migrations.AlterField(
            model_name='cachedata',
            name='cart_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 23, 5, 50, 28, 670951, tzinfo=utc), verbose_name='购物车添加时间'),
        ),
        migrations.AlterField(
            model_name='serviceparam',
            name='gmt_close',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 23, 5, 50, 28, 670301, tzinfo=utc), verbose_name='交易结束时间'),
        ),
        migrations.AlterField(
            model_name='serviceparam',
            name='gmt_create',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 23, 5, 50, 28, 670240, tzinfo=utc), verbose_name='交易创建时间'),
        ),
        migrations.AlterField(
            model_name='serviceparam',
            name='gmt_payment',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 23, 5, 50, 28, 670266, tzinfo=utc), verbose_name='交易付款时间'),
        ),
        migrations.AlterField(
            model_name='serviceparam',
            name='gmt_refund',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 23, 5, 50, 28, 670284, tzinfo=utc), verbose_name='交易退款时间'),
        ),
    ]
