# Generated by Django 2.0.4 on 2018-04-23 08:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20180423_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asynmsg',
            name='notify_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 23, 8, 9, 16, 696800, tzinfo=utc), verbose_name='通知时间'),
        ),
        migrations.AlterField(
            model_name='cachedata',
            name='cart_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 23, 8, 9, 16, 698180, tzinfo=utc), verbose_name='购物车添加时间'),
        ),
        migrations.AlterField(
            model_name='serviceparam',
            name='gmt_close',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 23, 8, 9, 16, 697581, tzinfo=utc), verbose_name='交易结束时间'),
        ),
        migrations.AlterField(
            model_name='serviceparam',
            name='gmt_create',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 23, 8, 9, 16, 697518, tzinfo=utc), verbose_name='交易创建时间'),
        ),
        migrations.AlterField(
            model_name='serviceparam',
            name='gmt_payment',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 23, 8, 9, 16, 697544, tzinfo=utc), verbose_name='交易付款时间'),
        ),
        migrations.AlterField(
            model_name='serviceparam',
            name='gmt_refund',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 23, 8, 9, 16, 697563, tzinfo=utc), verbose_name='交易退款时间'),
        ),
    ]
