# Generated by Django 2.0.4 on 2018-04-23 11:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20180423_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asynmsg',
            name='notify_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 23, 11, 34, 57, 553596, tzinfo=utc), verbose_name='通知时间'),
        ),
        migrations.AlterField(
            model_name='cachedata',
            name='cart_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 23, 11, 34, 57, 555143, tzinfo=utc), verbose_name='购物车添加时间'),
        ),
        migrations.AlterField(
            model_name='serviceparam',
            name='gmt_close',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 23, 11, 34, 57, 554416, tzinfo=utc), verbose_name='交易结束时间'),
        ),
        migrations.AlterField(
            model_name='serviceparam',
            name='gmt_create',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 23, 11, 34, 57, 554316, tzinfo=utc), verbose_name='交易创建时间'),
        ),
        migrations.AlterField(
            model_name='serviceparam',
            name='gmt_payment',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 23, 11, 34, 57, 554363, tzinfo=utc), verbose_name='交易付款时间'),
        ),
        migrations.AlterField(
            model_name='serviceparam',
            name='gmt_refund',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 23, 11, 34, 57, 554393, tzinfo=utc), verbose_name='交易退款时间'),
        ),
    ]
