# Generated by Django 2.0.4 on 2018-04-23 08:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20180423_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order_code',
            field=models.CharField(blank=True, max_length=249, null=True, verbose_name='订单编号'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 23, 8, 9, 16, 720826, tzinfo=utc), verbose_name='创建时间'),
        ),
    ]
