# Generated by Django 2.0.4 on 2018-04-23 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=120, null=True, unique=True, verbose_name='昵称')),
                ('phone', models.CharField(blank=True, max_length=120, null=True, unique=True, verbose_name='电话号码')),
                ('email', models.EmailField(blank=True, max_length=250, null=True, unique=True, verbose_name='邮箱')),
                ('user_pwd', models.CharField(max_length=250, verbose_name='登录密码')),
                ('log_time', models.DateTimeField(auto_now_add=True, verbose_name='登录起始时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('acc_status', models.IntegerField(default=1, verbose_name='帐号状态(num)')),
            ],
            options={
                'verbose_name': '用户帐号',
                'verbose_name_plural': '用户帐号',
            },
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('nickname', models.CharField(max_length=120, null=True, unique=True, verbose_name='昵称')),
                ('signature', models.CharField(blank=True, default='这个人很懒，什么也没留下。', max_length=250, null=True, verbose_name='个性签名')),
                ('realname', models.CharField(blank=True, default='未填写。', max_length=120, null=True, verbose_name='真实姓名')),
                ('face', models.ImageField(blank=True, default='web_site/default_face.png', null=True, upload_to='image/%Y/%m', verbose_name='头像')),
                ('sex', models.CharField(default='未填写。', max_length=8, null=True, verbose_name='性别')),
                ('birth', models.DateField(auto_now=True, verbose_name='生日')),
                ('sf_code', models.CharField(blank=True, default='未填写。', max_length=8, null=True, verbose_name='身份证号码')),
                ('is_member', models.NullBooleanField(default=None, verbose_name='是否是会员')),
                ('user_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.UserAccount', verbose_name='所属用户')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='用户id')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
            },
        ),
        migrations.CreateModel(
            name='UserMoneyRecord',
            fields=[
                ('user_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.UserAccount', verbose_name='所属用户')),
                ('use_money_count', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='在网站消费了多少钱')),
                ('product_num', models.IntegerField(null=True, verbose_name='已买多少件商品')),
                ('email', models.EmailField(blank=True, max_length=250, null=True, unique=True, verbose_name='保存的邮箱')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('data_status', models.IntegerField(default=1, verbose_name='数据状态')),
            ],
            options={
                'verbose_name': '用户消费记录',
                'verbose_name_plural': '用户消费记录',
            },
        ),
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('is_18', models.NullBooleanField(default=None, verbose_name='满18岁？')),
                ('is_marry', models.NullBooleanField(default=None, verbose_name='是否结婚')),
                ('is_house', models.NullBooleanField(default=None, verbose_name='是否有房')),
                ('is_car', models.NullBooleanField(default=None, verbose_name='是否有车')),
                ('credit_status', models.IntegerField(default=0, verbose_name='信誉状况(分)')),
                ('is_business', models.NullBooleanField(default=None, verbose_name='是否是商家')),
                ('is_real', models.NullBooleanField(default=None, verbose_name='是否实名认证')),
                ('user_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.UserAccount', verbose_name='所属用户')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='用户id')),
            ],
            options={
                'verbose_name': '用户状态详情',
                'verbose_name_plural': '用户状态详情',
            },
        ),
    ]
